<?php

namespace App\Livewire\Traits;

trait HasSkillData
{
    /**
     * Get all skill types
     * @return array
     */
    public function getSkillTypes(): array
    {
        return [
            'Actor',
            'Administrative',
            'Apparel Design',
            'Architecture',
            'Blog & Content Creator',
            'Bookkeeping',
            'Campaigns',
            'Car Service',
            'Carpenter',
            'Catering',
            'Cleaning Services',
            'Coach (Sports)',
            'Community',
            'Compliance',
            'Consulting',
            'Cooking',
            'Coordination',
            'Creative Arts',
            'Dairy Farming',
            'Data Analytics',
            'Diagnostics',
            'Digital Marketer',
            'Direction',
            'Distribution',
            'Electrical',
            'Email Campaign Setup',
            'Engineering',
            'Engineering Design',
            'Entertainment',
            'Event Management',
            'Fabrication',
            'Farming',
            'Film Production',
            'Financial Services',
            'Fish Breeding',
            'Garden Maintenance',
            'GIS Mapping',
            'Graphic Design',
            'Grievance Redressal',
            'Guiding',
            'Handicrafts',
            'Healthcare',
            'Home Nursing',
            'Home Repair',
            'Home Services',
            'Host',
            'Hotel Management',
            'Industrial Consulting',
            'Industrial Installation',
            'Industrial IT & Automation',
            'Industrial Logistics',
            'Industrial Maintenance',
            'Industrial Safety & Compliance',
            'Industrial Training Services',
            'Industrial Waste Management',
            'Insurance',
            'Integration',
            'Interior Design',
            'Interior Lighting',
            'Landscape Design',
            'Legal Support',
            'Logistics',
            'Luxury Rental',
            'Maintenance',
            'Makeup Services',
            'Management',
            'Manufacturing Services',
            'Marketing',
            'Mechanic',
            'Medicine Delivery',
            'Microenterprise',
            'Musician',
            'Online Learning',
            'Outdoor Ads',
            'Outstation Travel',
            'Painting',
            'Parcel Delivery',
            'Payroll',
            'Performance',
            'Performing Arts',
            'Personal Care',
            'Personal Training',
            'Pest Control',
            'Photographer',
            'Playback Singing',
            'Plumbing',
            'Pond Management',
            'Print Media',
            'Product Sales',
            'Project Management',
            'Real Estate',
            'Real Estate Photography',
            'Reconciliation',
            'Refereeing',
            'Rent',
            'Repair & Maintenance',
            'Sales',
            'SEO & SEM',
            'SHG Facilitation',
            'Software & App Development',
            'Software Operator',
            'Special Education',
            'Specialist Care',
            'Specialty Delivery',
            'Specialty Services',
            'Streaming',
            'Street Lighting',
            'Styling',
            'Subscription',
            'Supply',
            'Support',
            'Surveying',
            'Teacher (Academic)',
            'Template Design',
            'Theatre Performance',
            'Therapy',
            'Trainer (Skill)',
            'Transport',
            'Tutoring',
            'UI/UX Design',
            'Veterinary Care',
            'Videographer',
            'Visual Arts',
            'Volunteering',
            'Waste Management',
        ];
    }

    /**
     * Get all skill subtypes
     * @return array
     */
    public function getSkillSubtypes(): array
    {
        return [
            '2D/3D CAD Drafting',
            '3D Printing & Rapid Prototyping',
            '3D Rendering & Walkthroughs',
            'Academic Tutoring',
            'Accounting Software Training',
            'Acting & Film Workshops',
            'Acting & Performing Arts Classes',
            'Ad Campaigns',
            'Ad Concept & Script Writing',
            'Ad Copy & Taglines',
            'Ad Graphic Design',
            'Ad Placement & Media Buying',
            'Advertising Strategy Courses',
            'Aeration',
            'Affiliate Marketing in Amazon/Flipkart',
            'Affiliate Program Setup',
            'Agricultural Skill Training',
            'Agro Input Supply',
            'Agronomy Advisory',
            'Airport Pickup & Drop',
            'Analytics',
            'Animal Feed Supply',
            'Animation Explainer Video Creation',
            'Anniversary & Retirement Event Planning',
            'Apartment & House Rental',
            'API Integration Services',
            'App Development',
            'Appliance Electrical Repair',
            'Architectural Design',
            'Architecture Coaching & Software Training',
            'Assembly Line Setup',
            'Assignment Help',
            'At-home Salon Services',
            'Auto Rickshaw & Cab Ads',
            'Automation',
            'Automobile Repair',
            'AV Setup & Management',
            'B2B Equipment Sales',
            'Babysitting',
            'Background Scoring',
            'Bank & Ledger Reconciliation',
            'Bank Reconciliation',
            'Beautician Course Teaching',
            'Billboard Advertising',
            'Birthday Party Planning',
            'Blogging',
            'Blood Test & Imaging',
            'Brand & Promo Videos',
            'Breakdown Repair',
            'Bridal Makeup',
            'Brokerage Services',
            'Buffet Setup',
            'Building Plan Approval',
            'Bulb Replacement',
            'CAD Modelling',
            'CAD Prototyping',
            'Calibration & Testing',
            'Car Audio & Accessory Installation',
            'Car Wash & Detailing',
            'Career Counselling',
            'Casting',
            'Chemical Waste Handling',
            'CI/CD Pipeline Setup',
            'Circuit Design',
            'CNC Machining & Fabrication',
            'Coding',
            'Coding Bootcamps & Courses',
            'Cold Chain Logistics',
            'Commercial Space Optimization',
            'Commercial Video Production',
            'Community Outreach',
            'Company Law Compliance',
            'Competitive Exam Coaching',
            'Composting Setup',
            'Construction Project Management',
            'Contract Drafting & Review',
            'Conveyor System Setup',
            'Cooking Classes',
            'Corporate Event Planning',
            'Cosmetic Product Sales',
            'Course Creation',
            'Court Representation',
            'Credit Linkage',
            'Crowd Engagement',
            'Custom Component Manufacturing',
            'Custom Embroidery',
            'Custom Metal Work',
            'Custom Office Templates',
            'Custom Web Application Development',
            'Customer Handling',
            'Daily/Monthly Bookkeeping',
            'Dance',
            'Data Collection',
            'Deep Cleaning Services',
            'Dermatology/Cardiology/ENT',
            'Design & Illustration',
            'Desktop & Laptop Hardware Repair',
            'Diagnosis',
            'Diet Advice',
            'Dietary Customization',
            'Digital Record Keeping',
            'Dispatch',
            'Document Formatting & Cleanup',
            'Domestic Tour Planning',
            'Door & Furniture Repair',
            'Doubt Clearing',
            'Drafting',
            'Drain Cleaning',
            'Drama',
            'Driver-Based Car Hire',
            'Driving',
            'Drop shipping',
            'Dyslexia/Autism Support',
            'eBooks & Courses',
            'Educational YouTube Channel',
            'Effluent Treatment Services',
            'Electrical Panel Maintenance',
            'Electrical Safety Audit',
            'Electrical Wiring & Panel Setup',
            'Electrician Services',
            'Email Campaign Management',
            'Email Campaign Setup & Automation',
            'Email Etiquette & Productivity Training',
            'Email Troubleshooting & Recovery',
            'Emcee Services',
            'Energy Efficiency Consulting',
            'Enterprise Software Development',
            'Entrance Exam Coaching',
            'Environmental Compliance Audit',
            'Equipment Preventive Maintenance',
            'ERP Implementation',
            'Escalation',
            'EV Repair & Battery Service',
            'Event Catering',
            'Event Decor & Styling',
            'Event Logistics Management',
            'Event Security Services',
            'E-Waste Disposal',
            'Exam Prep',
            'Excel Macro & VBA Automation',
            'Fabric Selection',
            'Facial & Skin Care',
            'Factory Equipment Maintenance',
            'Factory Layout Planning',
            'Family Function Coordination',
            'Farm Equipment Rental',
            'Fashion Design Services',
            'Feed Management',
            'Feed Optimization',
            'Fertilizer Application',
            'Film & TV Acting',
            'Film Direction Services',
            'Film Editing & Post Production',
            'Finance Certification Coaching',
            'Financial Advisory',
            'Financial Literacy Training',
            'Financial Planning',
            'Financial Statement Preparation',
            'Fire Safety Audit',
            'Fish Feed Supply',
            'Fishery Advisory Services',
            'Fishery Skill Development',
            'Fitness Training',
            'Flyer & Brochure Distribution',
            'Food Blogging & Vlogging',
            'Food Delivery',
            'Forklift & Crane Operations',
            'Four-Wheeler Repair',
            'Freight & Bulk Transport',
            'Freshwater Fish Farming',
            'Fuse & Wiring Repair',
            'Fuse Replacement',
            'Game Development Services',
            'Gardening Workshops',
            'Garment Alteration',
            'General Physician Consultation',
            'Gents Tailoring',
            'Group Formation',
            'GST Filing',
            'GST Advisory',
            'Guest Handling',
            'Guest Services',
            'Guitar Lessons',
            'Haircut & Styling',
            'Handmade Apparel Sales',
            'Handmade Goods',
            'Handmade Instruments',
            'Hardscape Planning',
            'Hardware Troubleshooting & Diagnostics',
            'Hatchery Setup',
            'Hazardous Material Handling',
            'Hazardous Waste Handling',
            'Health Checkups',
            'HNI Portfolio Management',
            'Holiday Home & Villa Rental',
            'Home Appliance Installation',
            'Home Chef Services',
            'Home Garden Maintenance',
            'Homework Help',
            'Hotel & Flight Booking',
            'Housekeeping',
            'HVAC System Servicing',
            'Income Tax Filing',
            'Industrial Equipment Setup',
            'Industrial Freight & Transport',
            'Industrial Lighting Installation',
            'Industrial Machine Repair',
            'Industrial Machinery Installation',
            'Industrial Safety Audit',
            'Influencer Ad Campaigns',
            'Influencer Campaign Management',
            'Injection Melding',
            'Instrument Rental',
            'Instrument Repair',
            'Insurance Advisory',
            'Intercity Cab Booking',
            'Interior & Exterior Painting',
            'International Tour Planning',
            'Inventory Control Systems',
            'Investment Advisory',
            'IoT Sensor Deployment',
            'ISO Certification Support',
            'Jingle Creation',
            'Joint Fixing',
            'Keyword Research',
            'Ladies Tailoring',
            'Land Surveying',
            'Land Use Consulting',
            'Language Teaching',
            'Laptop/Desktop Repair',
            'Leak Fixing',
            'Leak Repair',
            'Leak Repair & Installation',
            'Lean Manufacturing Advisory',
            'Ledger Entry',
            'Legal Advisory',
            'Legal Consulting',
            'Legal Exam Coaching',
            'List Segmentation',
            'Live Band & DJ Booking',
            'Live Music & Dance Shows',
            'Live Music Performance',
            'Livelihood Skill Training',
            'Livestock Management Training',
            'Loan Application Assistance',
            'Local Courier Services',
            'Local Handicraft Production',
            'Local Tour Guide Services',
            'Location Scouting',
            'Logo Design',
            'Luxury Car Hire',
            'Machine Operation Training',
            'Machinery Installation',
            'Maintenance SOP Training',
            'Manicure & Pedicure',
            'Manuals & Documentation',
            'Map Creation',
            'Marketing Analytics & Reporting',
            'Marketing Strategy Consulting',
            'Match Referee',
            'Meal Box Subscription',
            'Meal Prep',
            'Mechanical Safety Inspection',
            'Medical Entrance Coaching',
            'Medication Administration',
            'Mental Health Therapy',
            'Menu Planning',
            'MES (Manufacturing Execution System)',
            'Milking',
            'Mobile App Development',
            'Mobile Repair',
            'Mock Tests',
            'Monthly Car Subscription',
            'MOOC & E-learning Platforms',
            'Mood Lighting Setup',
            'Movie Production Management',
            'MS Excel Training',
            'MS Word & PowerPoint Training',
            'Multilingual Content Translation',
            'Music & Dance Classes',
            'Music Arrangement',
            'Music Composition',
            'Music Licensing',
            'Music YouTube Channel',
            'Networking Device Repair',
            'NFT Creation',
            'NGO Program Management',
            'Nursing & Elderly Care',
            'Nutrition Consulting',
            'Office & Retail Space Rental',
            'Offline Marketing Strategy Training',
            'Online Community Building',
            'Online Content Streaming',
            'Online Grocery Delivery',
            'Optimization',
            'Order Packing',
            'Organic Farming Services',
            'Packaged Food Sales',
            'Painting',
            'Part Replacement',
            'Payroll Processing',
            'Peripheral Setup & Installation',
            'Personal Shopping',
            'Pest Control for Plants',
            'Pet Food & Essentials Delivery',
            'Pet Grooming',
            'Pharmacy Delivery',
            'Photo Retouching & Editing',
            'Photography',
            'Photography Workshops',
            'Physiotherapy & Rehab',
            'Piano Practice',
            'Pipe Installation',
            'Plant & Sapling Sales',
            'Plant Electrical Wiring',
            'Plant Selection',
            'PLC & Automation Setup',
            'Podcasting',
            'Polishing',
            'Pollution Check & Certification',
            'Pond Maintenance & Cleaning',
            'Poster Design',
            'PPE Supply & Training',
            'Printer & Scanner Repair',
            'Process Optimization',
            'Process Optimization Consulting',
            'Product & Brand Shoots',
            'Product Lifecycle Engineering',
            'Professional Email Setup',
            'Progress Tracking',
            'Project Guidance',
            'Property Documentation',
            'Property Shoots',
            'Property Valuation',
            'Pruning',
            'Public Speaking',
            'Recycling',
            'Refurbished Electronics Sales',
            'Regional Cuisine',
            'Rental Property Management',
            'Research Papers & Essays',
            'Residential Cleaning',
            'Residential Layout Planning',
            'Resolution Follow-up',
            'Restaurant Food Delivery',
            'Reverse Engineering',
            'RO & Water Purifier Service',
            'Robotics Programming',
            'Room Booking',
            'Route Optimization',
            'Route Planning',
            'Rural Microbusiness Setup',
            'Rural Product Marketing',
            'Safety Protocol Workshops',
            'SCADA System Integration',
            'School Curriculum Coaching',
            'School Teaching',
            'Scrap Collection & Recycling',
            'Script Rehearsal',
            'Sculpture',
            'Search Engine Marketing',
            'Search Engine Optimization',
            'Segregation',
            'Self-Drive Car Rental',
            'Self-Help Group Facilitation',
            'SEO & Marketing',
            'SEO Blog Writing',
            'Shared Accommodation Rental',
            'Sheet Metal Fabrication',
            'Sheet Metal Work',
            'Short Film & Web Series Production',
            'Site Safety Audit',
            'Sketching',
            'Skill Training',
            'Skill-Based Training Courses',
            'Smart Controls',
            'Social Awareness Event Planning',
            'Social Media Creatives',
            'Social Media Marketing',
            'Social Work Training',
            'Software Bug Fixing & Updates',
            'Software QA & Testing',
            'Sound Engineering',
            'Space Planning & Styling',
            'Spatial Analysis',
            'Spoken English',
            'Spoken English & Foreign Language Training',
            'Sports Blogging',
            'Sports Coaching',
            'Sports Commentary',
            'Sports Event Management',
            'Sports Physiotherapy',
            'Staff Deployment',
            'Stage Acting & Theatre Performance',
            'Stage Blocking',
            'Stand-up Comedy Booking',
            'Story & Script Writing',
            'Storyboarding',
            'Strategy Sessions',
            'Street Promotion & Sampling',
            'Structural Engineering',
            'Studio Portraits',
            'Studio Recording',
            'Subject Tutoring',
            'Supply Chain Strategy',
            'Tagline Creation',
            'Tailoring Classes',
            'Tax Audit Preparation',
            'Tax Dispute Resolution',
            'Taxation Courses',
            'Technical Skill Certification',
            'Technical Support',
            'Template Design',
            'Termite & Rodent Treatment',
            'Testing',
            'Ticket Logging',
            'Tiffin Services',
            'Timer Configuration',
            'Title Verification & Mutation',
            'Tool & Die Design',
            'Topic Research',
            'Translation & Localization',
            'Travel Insurance Advisory',
            'Two-Wheeler Repair',
            'Udemy/Skill share',
            'Upholstery',
            'User Testing',
            'Vaccination',
            'Vendor Coordination',
            'Vertical Garden Setup',
            'Veterinary Services',
            'Vibration & Thermal Analysis',
            'Video Editing & Post Production',
            'Videography Courses',
            'Vital Monitoring',
            'Vocal Training',
            'Voiceover & Narration',
            'Volunteer Coordination',
            'Wardrobe Planning',
            'Warehouse Setup & Management',
            'Water Quality Testing',
            'Web Development',
            'Website Copywriting',
            'Wedding & Function Coverage',
            'Wedding & Party Photography',
            'Wedding Catering',
            'Wedding Decor & Theme Design',
            'Wedding Photography',
            'Wedding Planning',
            'Wireframing',
            'Wiring',
            'Wiring Setup',
            'Workout Plans',
            'Writing & Editing',
            'Yoga Instruction',
            'YouTube Channel',
        ];
    }
}
